branches:
  only:
    - master

language: cpp

os:
  - linux
  - osx
  - windows

dist: bionic

env:
  - MSYSTEM="MINGW64"

before_install:
  - if [ $TRAVIS_OS_NAME == 'windows' ]; then choco install make --ignore-checksums; fi

script:
  - make -f Makefile.libretro -j 4 TARGET=mame SUBTARGET=tiny

