branches:
  only:
    - master

language: cpp

os:
  - linux
  - osx
  - windows

dist: bionic

env:
  - MSYSTEM="MINGW64" TARGET="mame" SUBTARGET="tiny" WINDRES="windres.exe"

before_install:
  - if [ $TRAVIS_OS_NAME == 'linux' ]; then sudo apt-get install libgl1-mesa-dev; fi
  - if [ $TRAVIS_OS_NAME == 'windows' ]; then choco install make --ignore-checksums; fi

script:
  - make -f Makefile.libretro -j 4

