branches:
  only:
    - master

language: cpp

env:
  - TARGET="mame" SUBTARGET="tiny"

matrix:
  include:
    - name: Linux
      dist: bionic
      before_install:
        - sudo apt-get install libgl1-mesa-dev
      script:
        - make -f Makefile.libretro -j 4
        - zip mame-${TRAVIS_OS_NAME}-${TRAVIS_CPU_ARCH}-${TRAVIS_TAG:1}.zip mametiny_libretro.so
    - name: Linux
      dist: bionic
      arch: arm64
      before_install:
        - sudo apt-get install libgl1-mesa-dev zip
      script:
        - make -f Makefile.libretro -j 4
        - zip mame-${TRAVIS_OS_NAME}-${TRAVIS_CPU_ARCH}-${TRAVIS_TAG:1}.zip mametiny_libretro.so
    - name: OSX
      os: osx
      osx_image: xcode11.2
      script:
        - make -f Makefile.libretro -j 4
        - zip mame-${TRAVIS_OS_NAME}-${TRAVIS_CPU_ARCH}-${TRAVIS_TAG:1}.zip mametiny_libretro.dylib
    - name: Windows
      os: windows
      before_install:
        - choco install make --ignore-checksums
      env:
        - MSYSTEM="MINGW64" MINGW64="C:/ProgramData/chocolatey"
      script:
        - make platform=win -f Makefile.libretro -j 4
        - 7z a mame-${TRAVIS_OS_NAME}-${TRAVIS_CPU_ARCH}-${TRAVIS_TAG:1}.zip mametiny_libretro.dll

